

export type MetricStatus = 'good' | 'warning' | 'critical';

export interface Owner {
  id: string;
  name: string;
  avatar: string; // URL
  role: string;
  department?: string; // New field
}

export interface KPI {
  id: string;
  title: string;
  value: string | number;
  unit?: string;
  target: string | number;
  trend: number; // Percentage change
  status: MetricStatus;
  category: 'Financial' | 'Operational' | 'SupplyChain' | 'Sales' | 'EHS';
  owner: Owner;
  comment?: string; // Required for Red Light items in WBR mode
  monetizationImpact?: string; // E.g., "$12k/day loss"
}

export interface Factory {
  id: string;
  name: string;
  type: 'Stamping' | 'Plating' | 'Molding' | 'Assembly';
  oee: number; // %
  scrapRate: number; // %
  safetyIncidents: number; // Count
  mpsAchievement: number; // %
  utilization: number; // %
  otdRegular: number; // %
  otdUrgent: number; // %
  otdNpi: number; // %
  outputValue: number; // $k
  wipDays: number; // Days
  // New Labor Metrics
  routingHours: number; // Standard Hours calculated from BOM/Routing
  clockedHours: number; // Actual Hours from Time & Attendance
  extraHours: number; // Overtime/Extra hours
}

export interface Issue {
  id: string;
  title: string;
  urgency: 'High' | 'Low';
  importance: 'High' | 'Low';
  owner: Owner;
  status: 'Open' | 'In Progress' | 'Escalated' | 'Closed';
  financialImpact: string;
  type: 'Quality' | 'Safety' | 'Delivery' | 'Cost';
  resolutionTime?: number; // Days
  is8D?: boolean; // Is an 8D report required?
  // New Fields for Task Management
  dueDate?: string;
  ownerDept?: string;
  resolutionIdea?: string;
  progress?: number; // 0-100%
  daysOverdue?: number;
  // NEW: Money-First & Causality Fields
  moneyAtRisk?: number; // Estimated loss if not fixed ($)
  sourceStream?: 'Lead' | 'Produce' | 'Order' | 'Source'; // Where did this come from?
  autoGenerated?: boolean; // Was this created by the system?
}

export interface CIPProject {
  id: string;
  name: string;
  stage: 'Idea' | 'Execution' | 'Finance Validation' | 'Completed';
  projectedSavings: number;
  validatedSavings: number;
  owner: string;
  department?: string;
  globalSupport?: boolean;
  year?: number;
}

// New Types for Tier N
export interface MaterialTrend {
  month: string;
  copper: number;
  resin: number;
  gold: number;
}

export interface WIPItem {
  stage: string;
  value: number; // $
  days: number; // Days of inventory
}

export interface CustomerProfitability {
  name: string;
  revenue: number; // $k
  margin: number; // %
  shareOfWallet: number; // %
}

export interface NPIProject {
  id: string;
  name: string;
  customer: string;
  sopDate: string;
  status: 'On Track' | 'At Risk' | 'Delayed';
  milestone: string;
  apqpPhase: 'Phase 2: Product Design' | 'Phase 3: Process Design' | 'Phase 4: Validation' | 'Phase 5: Launch';
  specDeviation: number; // % Deviation from requirement
  monthlyLoss: number; // $k Loss due to scrap/rework during ramp
  ytdLoss: number; // $k Year to date loss
  qualityIssue: string;
  riskDetails?: string; // Specific tooltip info for At Risk items
}

// New Type for "Lead to Ramp Up"
export interface MustWinProject {
    id: string;
    productCategory: 'Busbar' | 'Connector' | 'Interconnect' | 'Sensor';
    customer: string;
    revenue5Y: number; // Millions USD
    stage: 'Initial' | 'Quoting' | 'DFM' | 'Bidding' | 'Won';
    stageValue: number; // 1-5 for Scatter Plot
    issue: string;
    status: 'On Track' | 'Delayed' | 'Critical';
    winProbability: number; // 0-100%
}

// New Types for "Plan to Produce" Upgrade
export interface ProductionLoss {
    id: string;
    type: 'Machine' | 'Material' | 'Man' | 'Method' | 'Quality';
    description: string;
    workshop: string;
    duration: number; // Hours
    lossAmount: number; // $k
    rootCause: string;
}

export interface CapacityConstraint {
    id: string;
    process: string;
    constraintRatio: number; // % of total capacity limitation
    reason: string;
    owner: string;
    eta: string;
}

export interface InventoryAgingDetail {
    range: '0-30' | '31-90' | '91-180' | '>180';
    value: number; // $k
    description: string; // What materials/products
}

export interface InventoryTrend {
    month: string;
    totalValue: number; // $k
    target: number; // $k
}

// Grouped Inventory Data for Toggles
export interface InventoryDataCollection {
    all: { history: InventoryTrend[], aging: InventoryAgingDetail[] };
    roh: { history: InventoryTrend[], aging: InventoryAgingDetail[] };
    wip: { history: InventoryTrend[], aging: InventoryAgingDetail[] };
    fg: { history: InventoryTrend[], aging: InventoryAgingDetail[] };
}

export interface CapacityTrend {
    month: string;
    actualOutput: number; // % or Units
    plannedOutput: number; // % or Units
    dilEfficiency: number; // %
    idlEfficiency: number; // %
}

export interface COQBreakdown {
    category: 'Prevention' | 'Appraisal' | 'Internal Failure' | 'External Failure';
    value: number; // $k
    percentage: number; // %
}

export interface COQHistory {
    month: string;
    value: number; // $k
    target: number; // $k
    pctOfSales: number; // %
}

export interface ProductionVariance {
    workshop: string;
    varianceValue: number; // $k (Positive = Loss, Negative = Gain)
    reason: string;
    owner?: string;
}

export interface OutputFluctuation {
    date: string; // Day of month
    stamping: number; // Units/Value
    molding: number;
    plating: number;
    assembly: number;
}

export interface ProductProfitability {
    id: string;
    name: string;
    revenue: number; // $k
    margin: number; // %
    marginTarget: number; // %
    customer: string;
}

export interface OperationalIssue {
    id: string;
    workshop: string;
    issue: string;
    category: 'Equipment' | 'Material' | 'Quality' | 'Manpower' | 'Method';
    daysOpen: number;
    status: 'Open' | 'Escalated';
    owner: string;
    action: string;
}

// --- NEW TYPES FOR ORDER TO CASH (Automotive Focus) ---

export interface DemandForecast {
    month: string;
    forecast: number; // $k
    actual: number; // $k
}

export interface CustomerDemandProfile {
    id: string;
    name: string;
    type: 'Core' | 'Other';
    volatility: number; // %
    data: DemandForecast[];
    // New fields for AI Forecast Correction
    correctionFactor: number;
    historicalAccuracy: number;
    biasDescription: string;
}

export interface CostPassThroughDetail {
    customer: string;
    impactAmount: number; // $k
    recoveredAmount: number; // $k
    gap: number; // $k
    status: 'Recovered' | 'Negotiating' | 'Risk';
}

export interface YearDownEvent {
    id: string;
    customer: string;
    description: string;
    date: string; // Effective Date
    amount: number; // $k
    type: 'Year-Down' | 'Rebate';
}

export interface PremiumFreightDetail {
    id: string;
    customer: string;
    mode: 'Air' | 'Express Truck';
    amount: number; // $k
    reason: string;
}

export interface CoreCustomerStatus {
    id: string;
    name: string;
    type: 'OEM' | 'Tier1' | 'New Energy';
    otd: number; // %
    overdueDays: number;
    yearDownHitRate: number; // %
    volatility: number; // %
}

export interface CrossModuleImpact {
    id: string;
    customer: string;
    fluctuation: string; // e.g. "+20% YTD"
    impactLevel: 'High' | 'Medium' | 'Low';
    productionAction: string;
    status: 'Confirmed' | 'Pending';
}

export interface SalesRisk {
    id: string;
    customer: string;
    amount: number; // $k
    days: number;
    type: 'Overdue' | 'Dispute' | 'Volatility' | 'Cash';
    rating: 'A' | 'B' | 'C';
    details?: string;
}

export interface CashFlowWaterfallItem {
    name: string;
    value: number;
    fill: string;
    isTotal?: boolean;
}

// New: Customer Penalties
export interface CustomerPenalty {
    id: string;
    customer: string;
    type: 'Line Down' | 'Quality Claim' | 'Logistics';
    amount: number; // $k
    date: string;
    description: string;
    status: 'Open' | 'Negotiating' | 'Closed';
}

// --- NEW TYPES FOR SOURCE TO PAY (Optimization v2) ---

export interface CERRequest {
    id: string;
    project: string;
    amount: number;
    status: 'Approved' | 'Pending' | 'Rejected';
    requestDate: string;
    // New fields
    type: 'Emergency' | 'Design Change' | 'Capacity' | 'Quality';
    department: 'Production' | 'Facility' | 'Quality' | 'R&D';
    reason: string;
}

export interface SpendingTrend {
    month: string;
    // Granular MRO
    mroMaint: number;
    mroTools: number;
    mroConsumables: number;
    mroBudget: number;
    // Granular Spares
    sparesActual: number;
    sparesBudget: number; // Added budget for spares
    sparesDriver: string; // e.g., "Press A - Motor Failure"
}

export interface IQCLineStop {
    id: string;
    material: string;
    supplier: string;
    duration: number; // hours
    date: string;
}

export interface ProcurementException {
    id: string;
    type: 'Delay' | 'Supplier' | 'Budget';
    message: string;
    value: string;
    severity: 'High' | 'Medium';
}

export interface ProcurementCategorySpend {
    category: string;
    amount: number; // $k
}

export interface COPABreakdown {
    name: string;
    value: number;
}

// Keeping old types for backward compat if needed, though replaced
export interface MROTrend {
    month: string;
    budget: number;
    actual: number;
}

export interface SupplierBadPerf {
    id: string;
    name: string;
    isCore: boolean;
    issue: string;
    amountOrRate: string; // e.g. "$50k" or "15% Defect"
}

// --- NEW TYPES FOR COMMODITY MARKET MONITOR ---
export interface CommodityData {
    month: string;
    gold: number; // USD/oz
    silver: number; // USD/oz
    copper: number; // USD/Ton
}

export interface MarketIntelligence {
    id: string;
    title: string;
    date: string;
    severity: 'High' | 'Medium' | 'Low';
    source: string;
}

// --- NEW TYPES FOR STRATEGIC ECOSYSTEM DASHBOARD (Entity Health) ---

export interface StrategicPartner {
    id: string;
    name: string;
    type: 'Supplier' | 'Customer';
    subType: string; // e.g. Tier 1, OEM, New Energy
    score: number; // Health Score
    tags: string[]; // e.g., #TechMonopoly, #PriceWar
    changes: {
        type: 'Management' | 'Tech' | 'Risk' | 'Strategy' | 'Financial';
        desc: string;
    }[];
}

export interface MatrixData {
    name: string;
    innovation: number; // X-axis
    collaboration: number; // Y-axis
    spend: number; // Z-axis (size)
    category: 'Star' | 'CashCow' | 'Question' | 'Eliminate';
}

export interface EngagementEvent {
    id: string;
    date: string;
    title: string;
    partner: string;
    type: 'Meeting' | 'Negotiation' | 'Audit' | 'Visit';
    status: 'Past' | 'Future';
    outcome?: string; // For past events
    prep?: string; // For future events
}

export interface CustomerFunnelItem {
    tier: string;
    count: number;
    revenueShare: number; // %
    growth: number; // %
    desc: string;
}

// --- NEW TYPES FOR GM OPTIMIZATIONS (Daily Pulse, Risk Sim, Matrix View) ---

export interface DailyPulseData {
    date: string;
    // Updated Revenue Fields
    mtdRevenue: { val: number; target: number; status: 'good' | 'bad' }; // val is Actual MTD, target is Time-based Outlook Progress
    yesterdayRevenue: number; // PGI + Hub
    todayRisks: { count: number; desc: string };
    openActions: number;
    aiSummary: string;
    topFires: { title: string; owner: string; status: string }[];
}

export interface CustomerComplaint {
    id: string;
    customer: string;
    issue: string;
    status: 'Open' | 'D3 Submitted' | 'D8 Submitted' | 'Closed';
    owner: string;
    daysOpen: number;
    description: string;
}

export interface NewWonProject {
    id: string;
    project: string;
    customer: string;
    revenue: number; // $M (Lifetime or Annual)
    sop: string;
    image?: string;
}

export interface RiskPropagationStep {
    step: string;
    description: string;
    impact: string;
    status: 'Critical' | 'Warning';
}

export interface RiskPropagation {
    id: string;
    trigger: string;
    steps: RiskPropagationStep[];
    totalFinancialImpact: string;
}

export interface MatrixMetric {
    function: 'Quality' | 'Cost' | 'Inventory';
    metric: string;
    value: string;
    trend: number;
    stream: 'L2R' | 'P2P' | 'O2C' | 'S2P';
}

// --- NEW TYPES FOR CIP MODULE & ENHANCED ACTION CENTER ---

export interface CIPStat {
  label: string;
  value: string;
  trend: number; // YoY
}

export interface CIPDepartmentStat {
  department: string;
  share: number; // %
  target: number; // $k
  actual: number; // $k
}

export interface CIPHero {
  rank: number;
  name: string;
  department: string;
  avatar: string;
  contribution: string; // e.g., "3 Major Projects"
  savings: number; // $k
}

export interface InnovationStar {
  rank: number;
  name: string;
  department: string;
  avatar: string;
  score: number;
  patents: number;
}