
export type MetricStatus = 'good' | 'warning' | 'critical';

export interface Owner {
  id: string;
  name: string;
  avatar: string;
  role: string;
  department?: string;
}

export interface KPI {
  id: string;
  title: string;
  value: string | number;
  unit?: string;
  target: string | number;
  trend: number; 
  status: MetricStatus;
  category: 'Financial' | 'Operational' | 'SupplyChain' | 'Sales' | 'EHS';
  owner: Owner;
  comment?: string;
  monetizationImpact?: string;
}

export interface Factory {
  id: string;
  name: string;
  type: 'Stamping' | 'Plating' | 'Molding' | 'Assembly';
  oee: number;
  scrapRate: number;
  safetyIncidents: number;
  mpsAchievement: number;
  utilization: number;
  otdRegular: number;
  otdUrgent: number;
  otdNpi: number;
  outputValue: number;
  wipDays: number;
  routingHours: number;
  clockedHours: number;
  extraHours: number;
}

export interface Issue {
  id: string;
  title: string;
  urgency: 'High' | 'Low';
  importance: 'High' | 'Low';
  owner: Owner;
  status: 'Open' | 'In Progress' | 'Escalated' | 'Closed';
  financialImpact: string;
  type: 'Quality' | 'Safety' | 'Delivery' | 'Cost';
  dueDate?: string;
  ownerDept?: string;
  resolutionIdea?: string;
  progress?: number;
  daysOverdue?: number;
  moneyAtRisk?: number; 
  sourceStream?: 'Lead' | 'Produce' | 'Order' | 'Source';
  autoGenerated?: boolean;
}

export interface EHS_RISK {
  id: string;
  workshop: string;
  issue: string;
  risk: 'High' | 'Medium' | 'Low';
  owner: string;
}

export interface CIPProject {
  id: string;
  name: string;
  stage: 'Idea' | 'Execution' | 'Finance Validation' | 'Completed';
  projectedSavings: number;
  validatedSavings: number;
  owner: string;
  department?: string;
  globalSupport?: boolean;
}

// --- Business Stream Specific Types ---
export interface NPIProject {
  id: string;
  name: string;
  customer: string;
  sopDate: string;
  status: 'On Track' | 'At Risk' | 'Delayed';
  milestone: string;
  apqpPhase: string;
  specDeviation: number;
  ytdLoss: number;
}

export interface MustWinProject {
    id: string;
    productCategory: string;
    customer: string;
    revenue5Y: number;
    stage: string;
    stageValue: number;
    issue: string;
    status: string;
    winProbability: number;
}

export interface DemandForecast {
    month: string;
    forecast: number;
    actual: number;
}

export interface CustomerDemandProfile {
    id: string;
    name: string;
    volatility: number;
    correctionFactor: number;
    historicalAccuracy: number;
    biasDescription: string;
    data: DemandForecast[];
}

export interface StrategicPartner {
    id: string;
    name: string;
    type: 'Supplier' | 'Customer';
    subType: string;
    score: number;
    tags: string[];
    changes: { type: string; desc: string }[];
}
