import React, { useState, useEffect } from 'react';
import { X, Bot } from 'lucide-react';
import { useLanguage } from '../LanguageContext';
import { useTasks } from '../TaskContext';
import { Issue } from '../types';
import { OWNERS } from '../constants';

const GlobalTaskModal: React.FC = () => {
  const { t } = useLanguage();
  const { isModalOpen, closeTaskModal, addTask, prefilledTask, updateTask } = useTasks();
  
  // Local form state
  const [formData, setFormData] = useState<Partial<Issue>>({
    title: '', 
    urgency: 'High', 
    importance: 'High', 
    dueDate: '', 
    ownerDept: '', 
    status: 'Open'
  });

  const isEditing = !!(prefilledTask && prefilledTask.id && prefilledTask.id.includes('existing')); // Simple check if we passed an existing ID logic, though simplified here

  // Sync with prefilled data when modal opens
  useEffect(() => {
    if (isModalOpen && prefilledTask) {
        setFormData({
            ...prefilledTask,
            // Ensure defaults if missing
            urgency: prefilledTask.urgency || 'High',
            importance: prefilledTask.importance || 'High',
            status: prefilledTask.status || 'Open'
        });
    } else if (isModalOpen && !prefilledTask) {
        // Reset
        setFormData({
            title: '', 
            urgency: 'High', 
            importance: 'High', 
            dueDate: new Date().toISOString().split('T')[0], // Default today
            ownerDept: 'Operations', 
            status: 'Open'
        });
    }
  }, [isModalOpen, prefilledTask]);

  if (!isModalOpen) return null;

  const handleSave = () => {
      if (formData.id) {
          // Logic for updating existing task would go here if we implemented full edit in this modal
          // For now, this modal is primarily for NEW tasks triggered from insights
          updateTask(formData as Issue);
      } else {
          // Create New
          const newTaskFull: Issue = {
              id: `task-${Date.now()}`,
              title: formData.title || 'New Task',
              urgency: formData.urgency as any,
              importance: formData.importance as any,
              owner: OWNERS.ops, // Defaulting owner for simplicity
              ownerDept: formData.ownerDept,
              dueDate: formData.dueDate,
              status: 'Open',
              financialImpact: formData.financialImpact || 'TBD',
              type: formData.type || 'Cost',
              daysOverdue: 0,
              moneyAtRisk: formData.moneyAtRisk || 0,
              sourceStream: formData.sourceStream || 'Lead', // Default
              autoGenerated: !!formData.autoGenerated,
              // Add description or resolution idea
              resolutionIdea: formData.resolutionIdea
          };
          addTask(newTaskFull);
      }
      closeTaskModal();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4 animate-fade-in">
        <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-lg shadow-2xl animate-slide-up">
            <div className="p-6 border-b border-slate-700 flex justify-between items-center">
                <div className="flex items-center gap-3">
                    <h2 className="text-xl font-bold text-white">
                        {formData.id ? t('action.update_task') : t('action.create_task')}
                    </h2>
                    {formData.autoGenerated && (
                        <span className="flex items-center gap-1 text-[10px] font-bold text-cyan-400 bg-cyan-900/20 px-2 py-0.5 rounded border border-cyan-500/30">
                            <Bot size={12} /> Auto-Filled from Insight
                        </span>
                    )}
                </div>
                <button onClick={closeTaskModal} className="text-slate-400 hover:text-white"><X size={24} /></button>
            </div>
            
            <div className="p-6 space-y-4">
                {/* Title */}
                <div>
                    <label className="block text-xs font-bold text-slate-400 uppercase mb-1">{t('action.form.title')}</label>
                    <input 
                    type="text" 
                    className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm focus:border-blue-500 outline-none" 
                    value={formData.title} 
                    onChange={(e) => setFormData({...formData, title: e.target.value})}
                    />
                </div>
                
                {/* Urgency & Importance */}
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-xs font-bold text-slate-400 uppercase mb-1">{t('action.form.urgency')}</label>
                        <select 
                        className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm"
                        value={formData.urgency}
                        onChange={(e) => setFormData({...formData, urgency: e.target.value as any})}
                        >
                            <option value="High">{t('action.form.high')}</option>
                            <option value="Low">{t('action.form.low')}</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-slate-400 uppercase mb-1">{t('action.form.importance')}</label>
                        <select 
                        className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm"
                        value={formData.importance}
                        onChange={(e) => setFormData({...formData, importance: e.target.value as any})}
                        >
                            <option value="High">{t('action.form.high')}</option>
                            <option value="Low">{t('action.form.low')}</option>
                        </select>
                    </div>
                </div>

                {/* Due Date & Dept */}
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-xs font-bold text-slate-400 uppercase mb-1">{t('action.form.duedate')}</label>
                        <input 
                        type="date" 
                        className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm" 
                        value={formData.dueDate}
                        onChange={(e) => setFormData({...formData, dueDate: e.target.value})}
                        />
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-slate-400 uppercase mb-1">{t('action.form.dept')}</label>
                        <select 
                        className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm"
                        value={formData.ownerDept}
                        onChange={(e) => setFormData({...formData, ownerDept: e.target.value})}
                        >
                            <option value="">Select</option>
                            <option value="Finance">Finance</option>
                            <option value="Operations">Operations</option>
                            <option value="Quality">Quality</option>
                            <option value="SCM">SCM</option>
                            <option value="Sales">Sales</option>
                        </select>
                    </div>
                </div>

                {/* Description / Insight Context */}
                <div>
                    <label className="block text-xs font-bold text-slate-400 uppercase mb-1">Context / Description</label>
                    <textarea 
                        className="w-full bg-slate-800 border border-slate-700 rounded p-2 text-white text-sm h-24 focus:border-blue-500 outline-none"
                        value={formData.resolutionIdea || ''}
                        onChange={(e) => setFormData({...formData, resolutionIdea: e.target.value})}
                        placeholder="Details about the task or insight..."
                    />
                </div>

                <div className="flex justify-end gap-3 pt-4 border-t border-slate-700">
                    <button onClick={closeTaskModal} className="px-4 py-2 text-sm text-slate-400 hover:text-white transition-colors">Cancel</button>
                    <button onClick={handleSave} className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-lg shadow-lg transition-colors">
                        {formData.id ? 'Save Changes' : 'Add to Action Center'}
                    </button>
                </div>
            </div>
        </div>
    </div>
  );
};

export default GlobalTaskModal;