import React, { useState } from 'react';
import { CIP_KPI_STATS, DEPT_CIP_PERFORMANCE, CIP_HEROES, TOP_INNOVATORS, TOP_COMPLETED_CIP, TOP_ONGOING_CIP, RESOURCE_BOTTLENECKS, OWNERS } from '../constants';
import { Users, Plus, Edit3, TrendingUp, Target, Medal, Lightbulb, AlertTriangle, PieChart as PieChartIcon, Trophy, Star, Zap, ScanLine, Bot, Clock } from 'lucide-react';
import { useLanguage } from '../LanguageContext';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend, PieChart, Pie, Cell } from 'recharts';
import { Issue } from '../types';
import { useTasks } from '../TaskContext';

const ActionCenter: React.FC = () => {
  const { t } = useLanguage();
  const { tasks, addTask, openTaskModal } = useTasks();
  const [activeTab, setActiveTab] = useState<'tasks' | 'cip'>('tasks');
  
  // Auto-Scan State
  const [isScanning, setIsScanning] = useState(false);
  
  // Categorize issues for Matrix
  const q1 = tasks.filter(i => i.urgency === 'High' && i.importance === 'High');
  const q2 = tasks.filter(i => i.urgency === 'Low' && i.importance === 'High');
  const q3 = tasks.filter(i => i.urgency === 'High' && i.importance === 'Low');
  const q4 = tasks.filter(i => i.urgency === 'Low' && i.importance === 'Low');

  // Overdue Ranking Data
  const overdueTasks = tasks.filter(t => (t.daysOverdue || 0) > 0).sort((a, b) => (b.daysOverdue || 0) - (a.daysOverdue || 0));

  // CIP Totals Calculation
  const totalCompletedSavings = TOP_COMPLETED_CIP.reduce((acc, curr) => acc + curr.validatedSavings, 0);
  const totalOngoingSavings = TOP_ONGOING_CIP.reduce((acc, curr) => acc + curr.projectedSavings, 0);

  // Total Money At Risk Calculation
  const totalMoneyAtRisk = tasks.reduce((acc, curr) => acc + (curr.moneyAtRisk || 0), 0);

  const handleEditTask = (task: Issue) => {
      openTaskModal(task);
  };

  // Simulate Auto-Scan from Business Streams
  const handleAutoScan = () => {
      setIsScanning(true);
      setTimeout(() => {
          const newRisks: Issue[] = [
              { 
                  id: `auto-${Date.now()}-1`, 
                  title: 'Delay: PA66 Resin Material', 
                  urgency: 'High', importance: 'High', 
                  owner: OWNERS.supply, ownerDept: 'SCM', 
                  status: 'Open', 
                  financialImpact: 'Line Stop Risk', 
                  type: 'Delivery', 
                  moneyAtRisk: 15000, 
                  sourceStream: 'Source', 
                  autoGenerated: true,
                  dueDate: '2024-09-10'
              },
              { 
                  id: `auto-${Date.now()}-2`, 
                  title: 'BYD Order OTD Risk', 
                  urgency: 'High', importance: 'High', 
                  owner: OWNERS.sales, ownerDept: 'Sales', 
                  status: 'Open', 
                  financialImpact: 'Penalty Clause', 
                  type: 'Delivery', 
                  moneyAtRisk: 8000, 
                  sourceStream: 'Order', 
                  autoGenerated: true,
                  dueDate: '2024-09-12'
              }
          ];
          newRisks.forEach(r => addTask(r));
          setIsScanning(false);
      }, 1500);
  };

  return (
    <div className="space-y-6 animate-fade-in pb-10 relative">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
          <div>
              <h1 className="text-3xl font-bold text-white tracking-tight">{t('action.title')}</h1>
              <p className="text-slate-400 text-sm mt-1">Driving execution from profit-impacting alerts.</p>
          </div>
          
          {/* Tabs */}
          <div className="flex bg-slate-900 rounded-lg p-1 border border-slate-700">
              <button 
                  onClick={() => setActiveTab('tasks')}
                  className={`px-6 py-2 rounded-md text-sm font-bold uppercase transition-all flex items-center gap-2 ${activeTab === 'tasks' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
              >
                  <Users size={16} /> {t('action.tab_tasks')}
              </button>
              <button 
                  onClick={() => setActiveTab('cip')}
                  className={`px-6 py-2 rounded-md text-sm font-bold uppercase transition-all flex items-center gap-2 ${activeTab === 'cip' ? 'bg-ennovi-yellow text-slate-900 shadow-lg' : 'text-slate-400 hover:text-white'}`}
              >
                  <Lightbulb size={16} /> {t('action.tab_cip')}
              </button>
          </div>
      </div>

      {/* --- TAB 1: TASK MATRIX (MONEY FIRST REFACTOR) --- */}
      {activeTab === 'tasks' && (
        <div className="space-y-6 animate-fade-in">
            {/* Money At Risk Header (The GM Attention Grabber) */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-gradient-to-r from-red-900/40 to-slate-900 border-l-4 border-red-500 rounded-xl p-6 flex items-center justify-between shadow-lg">
                    <div>
                        <div className="text-red-400 font-bold uppercase tracking-wider text-xs mb-1 flex items-center gap-2">
                            <AlertTriangle size={16} className="animate-pulse" /> {t('action.money_at_risk')}
                        </div>
                        <div className="text-4xl font-black text-white flex items-baseline gap-2">
                            ${totalMoneyAtRisk.toLocaleString()}
                            <span className="text-sm font-medium text-slate-400">Total Potential Loss</span>
                        </div>
                    </div>
                    <div className="text-right">
                        <button 
                            onClick={handleAutoScan}
                            disabled={isScanning}
                            className="bg-red-600 hover:bg-red-500 text-white px-4 py-2 rounded-lg font-bold shadow-lg flex items-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {isScanning ? <ScanLine className="animate-spin" size={18} /> : <Zap size={18} />}
                            {isScanning ? t('action.scanning') : t('action.auto_scan')}
                        </button>
                        <div className="text-[10px] text-slate-400 mt-2">
                            Simulate pulling alerts from Streams
                        </div>
                    </div>
                </div>

                <div className="flex flex-col justify-end items-end gap-3">
                     <div className="flex gap-2">
                         <div className="flex items-center gap-2 bg-slate-800/50 px-3 py-1.5 rounded-lg border border-slate-700">
                             <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                             <span className="text-xs text-slate-300">Produce Stream</span>
                         </div>
                         <div className="flex items-center gap-2 bg-slate-800/50 px-3 py-1.5 rounded-lg border border-slate-700">
                             <div className="w-2 h-2 rounded-full bg-green-500"></div>
                             <span className="text-xs text-slate-300">Source Stream</span>
                         </div>
                         <div className="flex items-center gap-2 bg-slate-800/50 px-3 py-1.5 rounded-lg border border-slate-700">
                             <div className="w-2 h-2 rounded-full bg-purple-500"></div>
                             <span className="text-xs text-slate-300">Order Stream</span>
                         </div>
                     </div>
                     <button 
                        onClick={() => openTaskModal()}
                        className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-2 rounded-lg font-bold border border-slate-600 transition-colors"
                    >
                        <Plus size={18} /> {t('action.manual')}
                    </button>
                </div>
            </div>

            {/* Eisenhower Matrix with Money-First Cards - Height Optimized */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-auto">
                {/* Q1: Urgent & Important (High Value at Risk) - TALL */}
                <div className="bg-red-900/10 border border-red-500/30 rounded-2xl p-6 flex flex-col relative group hover:border-red-500/50 transition-all min-h-[320px] lg:min-h-[600px]">
                    <div className="absolute top-4 right-6 text-red-500 font-black opacity-10 text-6xl group-hover:opacity-20 transition-opacity">Q1</div>
                    <h3 className="text-red-400 font-bold mb-6 uppercase text-sm tracking-widest flex items-center gap-2">
                        <span className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></span>
                        {t('action.q1')} (High Impact)
                    </h3>
                    <div className="space-y-4 overflow-y-auto flex-1 custom-scrollbar pr-2">
                        {q1.map(issue => (
                            <TaskCard key={issue.id} issue={issue} onEdit={() => handleEditTask(issue)} />
                        ))}
                    </div>
                </div>

                {/* Q2 - TALL */}
                <div className="bg-blue-900/10 border border-blue-500/30 rounded-2xl p-6 flex flex-col relative group hover:border-blue-500/50 transition-all min-h-[320px] lg:min-h-[600px]">
                    <div className="absolute top-4 right-6 text-blue-500 font-black opacity-10 text-6xl group-hover:opacity-20 transition-opacity">Q2</div>
                    <h3 className="text-blue-400 font-bold mb-6 uppercase text-sm tracking-widest flex items-center gap-2">
                        <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                        {t('action.q2')}
                    </h3>
                    <div className="space-y-4 overflow-y-auto flex-1 custom-scrollbar pr-2">
                        {q2.map(issue => (
                            <TaskCard key={issue.id} issue={issue} onEdit={() => handleEditTask(issue)} />
                        ))}
                    </div>
                </div>

                {/* Q3 - SHORT (Half Height) */}
                <div className="bg-orange-900/10 border border-orange-500/30 rounded-2xl p-6 flex flex-col relative min-h-[320px] lg:min-h-[300px]">
                    <div className="absolute top-4 right-6 text-orange-500 font-black opacity-10 text-6xl">Q3</div>
                    <h3 className="text-orange-400 font-bold mb-6 uppercase text-sm tracking-widest">{t('action.q3')}</h3>
                    <div className="space-y-3 overflow-y-auto flex-1 custom-scrollbar pr-2">
                        {q3.map(issue => (
                            <TaskCard key={issue.id} issue={issue} onEdit={() => handleEditTask(issue)} simple />
                        ))}
                    </div>
                </div>

                {/* Q4 - SHORT (Half Height) */}
                <div className="bg-slate-800/30 border border-slate-700/50 rounded-2xl p-6 flex flex-col relative min-h-[320px] lg:min-h-[300px]">
                    <div className="absolute top-4 right-6 text-slate-600 font-black opacity-10 text-6xl">Q4</div>
                    <h3 className="text-slate-500 font-bold mb-6 uppercase text-sm tracking-widest">{t('action.q4')}</h3>
                    <div className="space-y-3 overflow-y-auto flex-1 custom-scrollbar pr-2">
                        {q4.map(issue => (
                            <TaskCard key={issue.id} issue={issue} onEdit={() => handleEditTask(issue)} simple dimmed />
                        ))}
                    </div>
                </div>
            </div>

            {/* Bottom Row: Analysis - Adaptive Layout */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 mt-6">
                {/* Resource Bottleneck */}
                <div className="glass-panel p-6 rounded-2xl border-l-4 border-purple-500">
                    <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                        <Users size={20} className="text-purple-500" />
                        {t('action.bottleneck_anal')}
                    </h3>
                    <div className="h-64">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={RESOURCE_BOTTLENECKS} layout="vertical" margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                                <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={false} stroke="#334155" opacity={0.3} />
                                <XAxis type="number" stroke="#94a3b8" tick={{fontSize: 10}} />
                                <YAxis dataKey="owner" type="category" stroke="#94a3b8" tick={{fontSize: 11}} width={90} />
                                <Tooltip contentStyle={{backgroundColor: '#0F172A', color: '#fff', fontSize: '10px'}} />
                                <Legend wrapperStyle={{fontSize: '10px'}} />
                                <Bar dataKey="open" stackId="a" fill="#3b82f6" name="Open Tasks" barSize={20} radius={[0, 4, 4, 0]} />
                                <Bar dataKey="overdue" stackId="a" fill="#EF4444" name="Overdue" barSize={20} radius={[0, 4, 4, 0]} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Overdue Ranking */}
                <div className="glass-panel p-6 rounded-2xl border-l-4 border-red-500">
                     <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                        <AlertTriangle size={20} className="text-red-500" />
                        {t('action.overdue_ranking')}
                    </h3>
                    <div className="overflow-y-auto max-h-64 custom-scrollbar pr-2 space-y-3">
                        {overdueTasks.map((t, idx) => (
                            <div key={t.id} className="flex items-center justify-between bg-slate-800/50 p-3 rounded border border-slate-700">
                                <div className="flex items-center gap-3">
                                    <div className="w-6 h-6 rounded-full bg-slate-700 text-slate-300 flex items-center justify-center text-xs font-bold">{idx + 1}</div>
                                    <div>
                                        <div className="text-sm font-bold text-white">{t.title}</div>
                                        <div className="text-xs text-slate-400">{t.owner.name}</div>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <div className="text-lg font-bold text-red-400 font-mono">{t.daysOverdue}</div>
                                    <div className="text-[10px] text-red-500 uppercase font-bold">Days Overdue</div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
      )}

      {/* --- TAB 2: CIP INNOVATION --- */}
      {activeTab === 'cip' && (
          <div className="space-y-6 animate-fade-in">
              {/* CIP KPIs */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {CIP_KPI_STATS.map((stat, idx) => (
                      <div key={idx} className="glass-panel p-6 rounded-2xl flex flex-col justify-between border-t-4 border-ennovi-yellow">
                          <div className="text-sm font-bold text-slate-400 uppercase tracking-wide">{t(`cip.kpi_${['savings', 'participation', 'count'][idx]}`)}</div>
                          <div className="text-4xl font-bold text-white mt-2">{stat.value}</div>
                          <div className="flex items-center gap-1 mt-2 text-green-400 text-xs font-bold bg-green-900/20 w-fit px-2 py-1 rounded">
                              <TrendingUp size={14} /> +{stat.trend}% YoY
                          </div>
                      </div>
                  ))}
              </div>

              {/* Charts Row */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* Dept Share Pie */}
                  <div className="glass-panel p-6 rounded-2xl">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><PieChartIcon size={18} className="text-blue-400" /> {t('cip.share')}</h3>
                      <div className="h-64">
                          <ResponsiveContainer width="100%" height="100%">
                              <PieChart>
                                  <Pie data={DEPT_CIP_PERFORMANCE} dataKey="share" nameKey="department" cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5}>
                                      <Cell fill="#3b82f6" />
                                      <Cell fill="#10B981" />
                                      <Cell fill="#F59E0B" />
                                      <Cell fill="#8b5cf6" />
                                  </Pie>
                                  <Tooltip 
                                    contentStyle={{backgroundColor: '#0F172A', color: '#fff', borderColor: '#334155'}} 
                                    itemStyle={{ color: '#E2E8F0' }}
                                  />
                                  <Legend layout="vertical" verticalAlign="middle" align="right" />
                              </PieChart>
                          </ResponsiveContainer>
                      </div>
                  </div>
                  {/* Target vs Actual Bar */}
                  <div className="glass-panel p-6 rounded-2xl">
                       <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><Target size={18} className="text-red-400" /> {t('cip.target_vs_act')}</h3>
                       <div className="h-64">
                           <ResponsiveContainer width="100%" height="100%">
                               <BarChart data={DEPT_CIP_PERFORMANCE}>
                                   <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.3} />
                                   <XAxis dataKey="department" stroke="#94a3b8" tick={{fontSize: 10}} />
                                   <YAxis stroke="#94a3b8" tick={{fontSize: 10}} />
                                   <Tooltip 
                                    contentStyle={{backgroundColor: '#0F172A', color: '#fff', borderColor: '#334155'}} 
                                    itemStyle={{ color: '#E2E8F0' }}
                                   />
                                   <Legend />
                                   <Bar dataKey="actual" name="Actual" fill="#10B981" radius={[4, 4, 0, 0]} />
                                   <Bar dataKey="target" name="Target" fill="#334155" radius={[4, 4, 0, 0]} />
                               </BarChart>
                           </ResponsiveContainer>
                       </div>
                  </div>
              </div>

              {/* Lists Row: Heroes & Innovators */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {/* Hero Board */}
                  <div className="glass-panel p-6 rounded-2xl border-l-4 border-ennovi-yellow bg-gradient-to-br from-yellow-900/10 to-transparent">
                      <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                          <Medal size={20} className="text-ennovi-yellow" /> {t('cip.hero_board')}
                      </h3>
                      <div className="space-y-4">
                          {CIP_HEROES.map(hero => (
                              <div key={hero.rank} className="flex items-center justify-between bg-slate-900/60 p-3 rounded-xl border border-yellow-500/20">
                                  <div className="flex items-center gap-4">
                                      <div className={`w-8 h-8 rounded-full flex items-center justify-center font-black text-slate-900 ${hero.rank === 1 ? 'bg-yellow-400' : hero.rank === 2 ? 'bg-slate-300' : 'bg-orange-400'}`}>
                                          {hero.rank}
                                      </div>
                                      <img src={hero.avatar} className="w-10 h-10 rounded-full border-2 border-slate-700" />
                                      <div>
                                          <div className="font-bold text-white">{hero.name}</div>
                                          <div className="text-xs text-slate-400">{hero.department} • {hero.contribution}</div>
                                      </div>
                                  </div>
                                  <div className="text-right">
                                      <div className="font-mono font-bold text-green-400">${hero.savings.toLocaleString()}</div>
                                      <div className="text-[10px] text-slate-500 uppercase">Savings</div>
                                  </div>
                              </div>
                          ))}
                      </div>
                  </div>

                  {/* Innovation Stars */}
                  <div className="glass-panel p-6 rounded-2xl border-l-4 border-blue-500 bg-gradient-to-br from-blue-900/10 to-transparent">
                      <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                          <Star size={20} className="text-blue-500" /> {t('cip.innovation_stars')}
                      </h3>
                      <div className="space-y-4">
                          {TOP_INNOVATORS.map(star => (
                              <div key={star.rank} className="flex items-center justify-between bg-slate-900/60 p-3 rounded-xl border border-blue-500/20">
                                  <div className="flex items-center gap-4">
                                       <div className="text-xl font-black text-blue-500/50 w-6 text-center">{star.rank}</div>
                                      <img src={star.avatar} className="w-10 h-10 rounded-full border-2 border-slate-700" />
                                      <div>
                                          <div className="font-bold text-white">{star.name}</div>
                                          <div className="text-xs text-slate-400">{star.department}</div>
                                      </div>
                                  </div>
                                  <div className="flex gap-6 text-right">
                                      <div>
                                          <div className="font-bold text-white">{star.patents}</div>
                                          <div className="text-[10px] text-slate-500 uppercase">Patents</div>
                                      </div>
                                      <div>
                                          <div className="font-bold text-blue-400">{star.score}</div>
                                          <div className="text-[10px] text-slate-500 uppercase">Score</div>
                                      </div>
                                  </div>
                              </div>
                          ))}
                      </div>
                  </div>
              </div>

              {/* Project Tables */}
              <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                  {/* Top Completed */}
                  <div className="glass-panel p-6 rounded-2xl">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><Trophy size={18} className="text-green-500" /> {t('cip.completed_projects')}</h3>
                      <div className="overflow-x-auto">
                          <table className="w-full text-left text-xs">
                              <thead>
                                  <tr className="text-slate-500 border-b border-slate-700">
                                      <th className="p-3">Project</th>
                                      <th className="p-3">Owner</th>
                                      <th className="p-3 text-right">Actual Savings</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {TOP_COMPLETED_CIP.map(p => (
                                      <tr key={p.id} className="border-b border-slate-800/50 hover:bg-slate-800/30">
                                          <td className="p-3 font-bold text-white">{p.name}</td>
                                          <td className="p-3 text-slate-400">{p.owner}</td>
                                          <td className="p-3 text-right font-mono text-green-400">${p.validatedSavings.toLocaleString()}</td>
                                      </tr>
                                  ))}
                                  {/* TOTAL ROW */}
                                  <tr className="bg-slate-800/50 border-t-2 border-slate-700">
                                      <td className="p-3 font-black text-white uppercase text-right" colSpan={2}>Total Savings</td>
                                      <td className="p-3 text-right font-mono font-black text-green-400 text-sm">${totalCompletedSavings.toLocaleString()}</td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>

                  {/* Top Ongoing */}
                  <div className="glass-panel p-6 rounded-2xl">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><Clock size={18} className="text-orange-500" /> {t('cip.ongoing_projects')}</h3>
                      <div className="overflow-x-auto">
                          <table className="w-full text-left text-xs">
                              <thead>
                                  <tr className="text-slate-500 border-b border-slate-700">
                                      <th className="p-3">Project</th>
                                      <th className="p-3">Owner</th>
                                      <th className="p-3 text-right">Proj. Savings</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {TOP_ONGOING_CIP.map(p => (
                                      <tr key={p.id} className="border-b border-slate-800/50 hover:bg-slate-800/30">
                                          <td className="p-3 font-bold text-white">{p.name}</td>
                                          <td className="p-3 text-slate-400">{p.owner}</td>
                                          <td className="p-3 text-right font-mono text-blue-400">${p.projectedSavings.toLocaleString()}</td>
                                      </tr>
                                  ))}
                                  {/* TOTAL ROW */}
                                  <tr className="bg-slate-800/50 border-t-2 border-slate-700">
                                      <td className="p-3 font-black text-white uppercase text-right" colSpan={2}>Total Projected</td>
                                      <td className="p-3 text-right font-mono font-black text-blue-400 text-sm">${totalOngoingSavings.toLocaleString()}</td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      )}
    </div>
  );
};

// Sub-component for Task Card (Money-First)
const TaskCard: React.FC<{ issue: Issue; simple?: boolean; dimmed?: boolean; onEdit: () => void }> = ({ issue, simple, dimmed, onEdit }) => {
    const { t } = useLanguage();
    
    // Determine source stream badge color
    const getStreamColor = (stream?: string) => {
        if (stream === 'Source') return 'bg-green-900/40 text-green-400 border-green-500/20';
        if (stream === 'Produce') return 'bg-blue-900/40 text-blue-400 border-blue-500/20';
        if (stream === 'Order') return 'bg-purple-900/40 text-purple-400 border-purple-500/20';
        if (stream === 'Lead') return 'bg-yellow-900/40 text-yellow-400 border-yellow-500/20';
        return 'bg-slate-800 text-slate-400';
    };

    return (
        <div className={`bg-slate-900/80 p-4 rounded-xl shadow-lg border-l-4 hover:translate-x-1 transition-transform relative ${
            dimmed ? 'opacity-60' : ''
        } ${
            issue.urgency === 'High' && issue.importance === 'High' ? 'border-red-500' :
            issue.urgency === 'Low' && issue.importance === 'High' ? 'border-blue-500' :
            issue.urgency === 'High' ? 'border-orange-500' : 'border-slate-600'
        }`}>
            {/* Source & Auto Badge */}
            <div className="flex justify-between items-center mb-2">
                <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 rounded border ${getStreamColor(issue.sourceStream)}`}>
                    {t('action.source_stream')}: {issue.sourceStream || 'N/A'}
                </span>
                {issue.autoGenerated && (
                    <span className="flex items-center gap-1 text-[9px] font-bold text-cyan-400 bg-cyan-900/20 px-1.5 py-0.5 rounded border border-cyan-500/30">
                        <Bot size={10} /> {t('action.auto_detected')}
                    </span>
                )}
            </div>

            <div className="flex justify-between items-start mb-2">
                <h4 className={`text-white font-bold text-sm leading-snug ${dimmed ? 'line-through text-slate-400' : ''}`}>
                    {t(`issue.${issue.id}`, issue.title)}
                </h4>
                {issue.owner?.avatar && <img src={issue.owner.avatar} className="w-8 h-8 rounded-full border border-slate-600" title={issue.owner.name} />}
            </div>
            
            {/* Money Impact Highlight */}
            {(issue.moneyAtRisk || 0) > 0 && !simple && (
                <div className="mb-2 bg-slate-800/60 p-2 rounded flex items-center justify-between border border-slate-700">
                    <span className="text-[10px] text-slate-400 font-bold uppercase">{t('action.impact')}</span>
                    <span className="text-red-400 font-mono font-bold text-sm">-${(issue.moneyAtRisk || 0).toLocaleString()}</span>
                </div>
            )}
            
            {!simple && (
                <div className="flex flex-wrap items-center gap-2 mt-2">
                     <span className="text-[10px] bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded border border-slate-700">
                         {issue.ownerDept || issue.owner?.department || 'Ops'}
                     </span>
                     {issue.dueDate && (
                         <span className="text-[10px] bg-slate-800 text-slate-300 px-1.5 py-0.5 rounded border border-slate-700 flex items-center gap-1">
                             <Clock size={10} /> {issue.dueDate}
                         </span>
                     )}
                </div>
            )}
            
            <button 
                onClick={onEdit}
                className={`mt-3 w-full py-1.5 text-xs rounded-lg font-bold uppercase tracking-wide transition-colors flex items-center justify-center gap-2 ${
                    issue.urgency === 'High' ? 'bg-red-600/20 text-red-400 hover:bg-red-600 hover:text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                }`}
            >
                <Edit3 size={12} /> {t('action.edit')}
            </button>
        </div>
    )
}

export default ActionCenter;